# Generated by Django 4.2.3 on 2023-07-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_comment_author_remove_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo', verbose_name='이미지'),
        ),
    ]
